# Generated by Django 4.0.3 on 2022-04-18 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('asking_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_mobile', models.PositiveIntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('asking_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company')),
            ],
        ),
    ]
