# Generated by Django 4.0.4 on 2022-04-19 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_condition_alter_car_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('asking_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_mobile', models.IntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company')),
            ],
        ),
    ]
