# Generated by Django 4.0.3 on 2022-05-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_query2'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing2',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='seller_name',
            field=models.CharField(max_length=100),
        ),
    ]
