# Generated by Django 4.0.3 on 2022-05-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_listing2_status_alter_listing2_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing2',
            name='status',
        ),
        migrations.RemoveField(
            model_name='query2',
            name='query_id',
        ),
        migrations.AddField(
            model_name='listing2',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.query2'),
        ),
    ]
