# Generated by Django 4.0.3 on 2022-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_listing2_status_remove_query2_query_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query2',
            name='car_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='query2',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='query2',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
